    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/bootstrap.min.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/owl.carousel.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/owl.theme.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/owl.transitions.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/meanmenu/meanmenu.min.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/animate.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/summernote/summernote.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/themesaller-forms.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/bootstrap-select/bootstrap-select.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/normalize.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/scrollbar/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/jvectormap/jquery-jvectormap-2.0.3.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/notika-custom-icon.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/wave/waves.min.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/main.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>style.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>new-style.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/responsive.css">
    <script src="<?= assetsUrl(); ?>js/vendor/modernizr-2.8.3.min.js"></script>
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/color-picker/farbtastic.css">
    <link rel="stylesheet" href="<?= assetsUrl(); ?>css/datapicker/datepicker3.css">